language: java
jdk:
- oraclejdk8
notifications:
  email: false
branches:
  only:
  - master
after_success: gradle :uploadArchives
env:
  global:
  - secure: 7EYphHWvUdnq/m4aYJraFL59Ab21j+5JAaALo2H5JWkORBGnM41keRd24l4IDEvcSErdl9U0r6ULvLdfGc+4OL7CaZdTP9lQMMrAjVY62fZ476s/rUC6ZCeJqA+MXNOJh4OJDdJ3No7nVtkMd0p5A55Jiko+EhQdQ4QgxIQXwJ2BhwhREWzi3tKmHcZ3Un8dG4MzGcl5VYjxLEwPIUS77etfpDHDZ74MTz0s7bfV/75vxRJnjzMaa2mnYZeUZlHZjbEihxt7MaVJTgdAadRR9FOjDUR/Qy/3yBwKqUYZ46+1BGcjGO/B1OSElDuEquX42cWeW36ibwz7SVbxlBx1Mk3IOWLmFbydSO5sa55SxfJQC6V7XxGBzcC8vLfZ2wJpgOOAS3AxVoaJ2Nf0X0MafESMTKtfIUVSuvBcQr7i/hncnrmKdTzQSlsy8AHMuYrwGU5X/hIvF+2mm8v2AA/R3Brp0TdfK+JiNmxHakSnTr1X2f11IF19TTFpjTf0W0V0IQ3HGNkgo8VbgiukSLtsQz1u1OjbaTJ3EfE2Os8PCG2yN3MvMkoOrd7jxL11KLmrMilsRS4oMOnijuSmA+nxB5Bu31FUTj5u4U5MfFrOOdv1S5fuFr/IZwbS+JWVl6lVlMeP88uLwF+jyAeBtRxbC7eBFaF+Ct4QAbyQhXAiAuo=
  - secure: 3SNfC/Jpu0RzlwOIZ0adK6fbWLZ0SvsyFDCrcKAHWppJxAjHuFT/P8cwVH+RMF3QZvw28C8ZSQdPZkQgu0d8EKvQsi1TlP3ewBeca8RqU2WfuDmZbPCUVoFQjjKZ6pasrib4erQGUSyAzEcisDqlKJf1VrPKkVHqgyO5Yx75pthoB1c1qofBplbh3chZ333xcZHnjtIYCqlpplfh8qbonAL4xMD4NLqoEY2OyTylEY2+BC6C6AB9YxjkQdrmNw6uC1pYdhD7tapzzROYQ5nHs4o9yFObq0mOgelnLdkNdM89lGo3of3wjW2miBgEnh7bbWiOpHY6RaJky1CduX0jUQs+TbfL1bkTyEe/QDJTXSqgTn0kx1B7PQFomIL4fcBe26qJ8GvDgKY2rvuBMBMON3TB8xwtrb35z+3nBP4SyqJKa9ShuMvo8Yy5JHXgQqui1RW8AljQJE1q7kUN5vZMQ+5muyBypeNgVoRhlK+cRiLTs8eL4zMwtrxDhkJ22/igCIpXrTm2XmnDHHbO9Pqd5DEFN3Ypk3n6FvLfEC8/TYuUTHrmEj9df9u14NT3qYyy7nTdm24fUPSqK4QgwecBpSU2dI5wXiWjpS3dh5PCNo5A0YV88GVWTveKsySFQc+ad+ceo7b1XzjE1FPVc37XtGymyYK6rnvF6BcR7jGLpkQ=
