name: SimpleWiki
version: '$version'
main: me.drewhoener.wiki.SimpleWiki
commands:
  testing:
    description: testing
    usage: /testing
  wiki:
    description: Base wiki command
    usage: /wiki [pluginwiki] [category] [subcat]
    aliases: [swiki]
  reindex:
    description: Reloads wiki
    usage: /reindex